config/routes.rb
Rails.application.routes.draw do
  
  get 'mobility/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'home/index'
  
  # devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/logout', :to => 'sessions#destroy'
  get '/login', :to => 'sessions#new', :as => :login
  resources :users
  root to: 'pages#login'
  get 'pages/dashboard', :to => 'dashboard#index'
  get 'pages/dashboard/physician', :to =>'physician#index'
  # post 'pages/physician-create-account', :to =>'physician#create_account'
  post 'pages/dashboard', :to => 'dashboard#index'
  get 'pages/connections', :to => 'connection#index'
  get 'pages/profile', :to => 'profile#index'
  post 'pages/profile/add_physician', :to=>'profile#add_physician'
  post 'pages/profile/update_user_info', :to=>'profile#update_user_info'
  # post 'pages/profile', :to => 'profile#index'
  get 'pages/foodlog', :to => 'foodlog#index'
  get 'pages/foodlog/data', :to => 'foodlog#get_edamam_data' , :as => 'get_edamam_data' 
  post 'pages/foodlog/log', :to => 'foodlog#log_food', :as => 'log_food'
  get 'pages/mobility', :to => 'mobility#index'
  post 'pages/mobility', :to => 'mobility#index'
  get 'pages/sleep', :to => 'sleep#index'
  post 'pages/sleep', :to => 'sleep#index'
  # get 'pages/foodlog/recipes', :to => 'foodlog#render'
  get 'pages/login'
  post 'pages/create-physician-account', :to => 'pages#create_physician_account'
  # get 'pages/register'
  # get 'pages/recipes'
  get 'pages/dashboard/physician-questions', :to=> 'user_questions#index'
  post 'pages/dashboard/physician-questions', :to=> 'user_questions#send_responses'
  post 'pages/profile/remove_physician', :to=>'profile#remove_physician'
  post 'pages/dashboard/physician/get_user_data',  :to =>'physician#get_user_data'
  get  'pages/dashboard/physician/get_user_data',  :to =>'physician#get_user_data'
  post 'question/create', :to => 'question#create'
  post 'question/delete', :to => 'question#delete_questions'
  get  'image/upload', :to => 'image#upload'
  post 'image/send_packet', :to => 'image#send_packet', :as => 'send_packet'
  post 'image/delete', :to => 'image#delete_image', :as => 'delete_image'

  post 'pages/dashboard/delete-event', :to => 'dashboard#delete_event', :as => 'delete_user_events'
  post 'pages/dashboard/update-event', :to => 'dashboard#update_event', :as => 'update_user_events'
  get 'pages/exposome', :to => 'exposome#index'
  post 'pages/exposome', :to => 'exposome#index'
  get 'pages/exposome/get_exposome_data', :to => 'exposome#get_exposome_data', :as => 'get_exposome_data'

  get 'pages/user/create_question', :to => 'create_user_questions#index'
  post 'pages/user/create_question', :to => 'create_user_questions#create'
  delete 'pages/user/create_question',  :to => 'create_user_questions#destroy'

  post 'pages/user/send_responses', :to => 'create_user_questions#send_responses'
  get 'pages/user/responses', :to => 'user_responses#index'
  post 'pages/user/responses', :to => 'user_responses#index'

  get 'pages/notifications', :to => 'notification#index'
  post 'pages/notifications/mark_notification_as_read', :to => 'notification#mark_notification_as_read'
  get 'pages/dashboard', to: 'dashboard#geocode'
  get 'physician/questions', :to=> 'user_questions#get_physicians_questions'
  get 'api/physicians', :to=> 'physicians_api#get_users_physicians' #  get physicians for a user
  get 'api/physicians/all', :to=> 'physicians_api#get_all_physicians' #  get  all physicians
  
  get 'api/physician/:id', :to=> 'physicians_api#get_physician' # get specific physician
  post 'api/update/user', :to=> 'profile#update_user'   # update user profile
  get 'api/user', :to=> 'profile#get_user'    # get specific user
  post 'api/user/physicians', :to=> 'profile#add_physicians_api' #  add physicians to user
  # get 'api/user/physicians', :to=> 'profile#get_users_physicians_api' #  get users physicians
  post 'api/user/physicians/remove', :to=> 'profile#remove_physicinas_api' #  remove user physicians
  
  get 'pages/mobility/last_month', to: 'mobility#last_month' #get last month's mobility data
  # get 'pages/mobility/last_week', to: 'mobility#last_week', as: 'last_week' 
  # post 'pages/mobility/last_week', to: 'mobility#last_week', as: 'last_week' 

  get 'pages/mobility/pick_date', to: 'mobility#pick_date', as: 'pick_date' #get path to pick_date from the _bar_totalsteps_dayandweek.html.erb 
end

app/views/pages/logged_out/_footer.html.erb
<footer class="py-5" id="footer-main">
  <div class="container">
    <div class="row align-items-center justify-content-xl-between">
      <div class="col-xl-6">
        <div class="copyright text-center text-xl-left text-muted">
          &copy; 2022 <a href="https://personicle.org" class="font-weight-bold ml-1" target="_blank">Personicle (An initiative by Clearsense)</a>
        </div>
      </div>
      <div class="col-xl-6">
        <ul class="nav nav-footer justify-content-center justify-content-xl-end">
          <li class="nav-item">
            <a href="https://personicle.org" class="nav-link" target="_blank">Personicle</a>
          </li>
          <li class="nav-item">
            <a href="https://personicle.org/about" class="nav-link" target="_blank">About Us</a>
          </li>
          <li class="nav-item">
            <a href="https://personicle.org/blog" class="nav-link" target="_blank">Resources</a>
          </li>
          <%# <li class="nav-item">
            <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
          </li> %>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/pages/logged_out/_topnav.html.erb
<nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">

  <div class="container">
    <a class="navbar-brand" href="/">
      <%= image_tag 'brand/personicle-logo-5.png' %>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
            <a href="dashboard.html">
              <%= image_tag 'brand/personicle-logo-5.png' %>
            </a>
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="<%= pages_dashboard_path %>" class="nav-link">
            <span class="nav-link-inner--text">Dashboard</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="<%= pages_login_path %>" class="nav-link">
            <span class="nav-link-inner--text">Login</span>
          </a>
        </li>
        <li class="nav-item">
          <%= render 'layouts/messages' %>
        </li>
  
        <%# <li class="nav-item">
          <a href="<%= pages_register_path %>
          <%# class="nav-link"> %>
            <%# <span class="nav-link-inner--text">Register</span>
          </a>
        </li> %>
      </ul>
      <hr class="d-lg-none" />
      <ul class="navbar-nav align-items-lg-center ml-lg-auto">
        <%# <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://www.facebook.com/creativetim" target="_blank" data-toggle="tooltip" data-original-title="Like us on Facebook">
            <%= fa_icon 'facebook' %>
            <%# <span class="nav-link-inner--text d-lg-none">Facebook</span>
          </a>
        </li>  %>
        <%# <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://www.instagram.com/creativetimofficial" target="_blank" data-toggle="tooltip" data-original-title="Follow us on Instagram">
            <%= fa_icon 'instagram' %>
            <%# <span class="nav-link-inner--text d-lg-none">Instagram</span>
          </a> 
        </li> %>
        <%# <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://twitter.com/creativetim" target="_blank" data-toggle="tooltip" data-original-title="Follow us on Twitter">
            <%= fa_icon 'twitter' %>
            <%# <span class="nav-link-inner--text d-lg-none">Twitter</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="https://github.com/vin-clearsense/Personicle" target="_blank" data-toggle="tooltip" data-original-title="Star us on Github">
            <%= fa_icon 'github' %>
            <%# <span class="nav-link-inner--text d-lg-none">Github</span>
          </a>
        </li>  %>
        <%# <li class="nav-item d-none d-lg-block ml-lg-4">
          <a href="https://www.creative-tim.com/product/argon-dashboard-pro?ref=ad_upgrade_pro" target="_blank" class="btn btn-neutral btn-icon">
            <span class="btn-inner--icon">
               <%= fa_icon 'shopping-cart', class: "fas mr-2" %>
            <%# </span>
            <span class="nav-link-inner--text">Upgrade to PRO</span>
          </a>
        </li>  %>
      </ul>
    </div>
  </div>
</nav>