config/routes.rb
Rails.application.routes.draw do
  
  get 'mobility/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'home/index'
  
  # devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/logout', :to => 'sessions#destroy'
  get '/login', :to => 'sessions#new', :as => :login
  resources :users
  root to: 'pages#login'
  get 'pages/dashboard', :to => 'dashboard#index'
  get 'pages/dashboard/physician', :to =>'physician#index'
  # post 'pages/physician-create-account', :to =>'physician#create_account'
  post 'pages/dashboard', :to => 'dashboard#index'
  get 'pages/connections', :to => 'connection#index'
  get 'pages/profile', :to => 'profile#index'
  post 'pages/profile/add_physician', :to=>'profile#add_physician'
  post 'pages/profile/update_user_info', :to=>'profile#update_user_info'
  # post 'pages/profile', :to => 'profile#index'
  get 'pages/foodlog', :to => 'foodlog#index'
  get 'pages/foodlog/data', :to => 'foodlog#get_edamam_data' , :as => 'get_edamam_data' 
  post 'pages/foodlog/log', :to => 'foodlog#log_food', :as => 'log_food'
  get 'pages/mobility', :to => 'mobility#index'
  post 'pages/mobility', :to => 'mobility#index'
  get 'pages/sleep', :to => 'sleep#index'
  post 'pages/sleep', :to => 'sleep#index'
  # get 'pages/foodlog/recipes', :to => 'foodlog#render'
  get 'pages/login'
  post 'pages/create-physician-account', :to => 'pages#create_physician_account'
  # get 'pages/register'
  # get 'pages/recipes'
  get 'pages/dashboard/physician-questions', :to=> 'user_questions#index'
  post 'pages/dashboard/physician-questions', :to=> 'user_questions#send_responses'
  post 'pages/profile/remove_physician', :to=>'profile#remove_physician'
  post 'pages/dashboard/physician/get_user_data',  :to =>'physician#get_user_data'
  get  'pages/dashboard/physician/get_user_data',  :to =>'physician#get_user_data'
  post 'question/create', :to => 'question#create'
  post 'question/delete', :to => 'question#delete_questions'
  get  'image/upload', :to => 'image#upload'
  post 'image/send_packet', :to => 'image#send_packet', :as => 'send_packet'
  post 'image/delete', :to => 'image#delete_image', :as => 'delete_image'

  post 'pages/dashboard/delete-event', :to => 'dashboard#delete_event', :as => 'delete_user_events'
  post 'pages/dashboard/update-event', :to => 'dashboard#update_event', :as => 'update_user_events'
  get 'pages/exposome', :to => 'exposome#index'
  post 'pages/exposome', :to => 'exposome#index'
  get 'pages/exposome/get_exposome_data', :to => 'exposome#get_exposome_data', :as => 'get_exposome_data'

  get 'pages/user/create_question', :to => 'create_user_questions#index'
  post 'pages/user/create_question', :to => 'create_user_questions#create'
  delete 'pages/user/create_question',  :to => 'create_user_questions#destroy'

  post 'pages/user/send_responses', :to => 'create_user_questions#send_responses'
  get 'pages/user/responses', :to => 'user_responses#index'
  post 'pages/user/responses', :to => 'user_responses#index'

  get 'pages/notifications', :to => 'notification#index'
  post 'pages/notifications/mark_notification_as_read', :to => 'notification#mark_notification_as_read'
  get 'pages/dashboard', to: 'dashboard#geocode'
  get 'physician/questions', :to=> 'user_questions#get_physicians_questions'
  get 'api/physicians', :to=> 'physicians_api#get_users_physicians' #  get physicians for a user
  get 'api/physicians/all', :to=> 'physicians_api#get_all_physicians' #  get  all physicians
  
  get 'api/physician/:id', :to=> 'physicians_api#get_physician' # get specific physician
  post 'api/update/user', :to=> 'profile#update_user'   # update user profile
  get 'api/user', :to=> 'profile#get_user'    # get specific user
  post 'api/user/physicians', :to=> 'profile#add_physicians_api' #  add physicians to user
  # get 'api/user/physicians', :to=> 'profile#get_users_physicians_api' #  get users physicians
  post 'api/user/physicians/remove', :to=> 'profile#remove_physicinas_api' #  remove user physicians
  
  get 'pages/mobility/last_month', to: 'mobility#last_month' #get last month's mobility data
  # get 'pages/mobility/last_week', to: 'mobility#last_week', as: 'last_week' 
  # post 'pages/mobility/last_week', to: 'mobility#last_week', as: 'last_week' 

  get 'pages/mobility/pick_date', to: 'mobility#pick_date', as: 'pick_date' #get path to pick_date from the _bar_totalsteps_dayandweek.html.erb 
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
require 'json'
require 'ostruct'
require 'date'
before_action :require_user, :session_active?, :get_user_notifications

    def user_mobility
        url = 'http://localhost:3000/steps.json'
        #logger.info 'url: ' + url
        puts session[:oktastate]
        res = RestClient::Request.execute(:url => url, headers: {Authorization: "Bearer #{session[:oktastate]['credentials']['token']} "}, :method => :get, :verify_ssl => false)
        #puts res
        if res
            #hash = JSON.parse(res)
            #res.strip("\"dateTime": \"")
            #res.gsub!(/^*("\"dateTime: \"")*$/, '')

            #res.strip(", \"value\"")
            #res.gsub!(/^*(", \"value\"")*$/, '')


            #str = "{\"dateTime\": \"2020-03-31 23:59:00\", \"value\": \"0\"}"
            #str.gsub(/v/, '*')
            #str.strip!


            #logger.info "res" + str
            @dashboards = JSON.parse(res)
            
        end

        # logger.info "hi friends" + "#{@dashboards.flat_map { |role| role["dateTime"].tr('"', '') + ' : ' + role["value"].tr('"', '') }}"
        
        #@copy1 = @dashboards.map(&:values).select {|dateTime, values| values["dateTime"] != 0}
        #logger.info "#{@copy1.to_json}"

        logger.info "#{@dashboards}"
        #logger.info 'Chart Controller: ' + "#{@dashboards[0]}"
        # render json: {"dateTime": "2020-03-31 23:59:00", "value": "0"}
        # render json: @dashboards#.group_by_day(:created_at).count
        render json: @dashboards#.group_by_day(:created_at).count
        #render json: MultiJson.dump(@dashboards)
        #render json: @dashboards.flat_map { |role| role["dateTime"] + ' : ' + role["value"] }

    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  require 'json'
  require 'ostruct'
  require 'date'
  before_action :require_user, :session_active?, :get_user_notifications
  before_action :set_locale

  protected def set_locale
    I18n.locale = params[:locale] || # 1: use request parameter, if available
      session[:locale] ||            # 2: use the value saved in iurrent session
      I18n.default_locale            # last: fallback to default locale
  end

  protected def save_locale
    session[:locale] = I18n.locale
  end

  def index
    # puts params
    puts session[:oktastate]['credentials']['token']
    # if !params[:noti_id].nil? &&  !params[:noti_id].blank? 
    #   @notification_read = Notification.find_by(id: params[:noti_id]).mark_as_read!
    # end
    st = 3.months.ago.strftime("%Y-%m-%d %H:%M:%S.%6N")
    et = Time.now.strftime("%Y-%m-%d %H:%M:%S.%6N")

    if params[:refresh]=="hard_refresh"
      puts "hard refresh"
      @response = FetchData.get_events(session,event_type=false,st,et,hard_refresh=true,uid=session[:oktastate]['uid'])
      @response_step = FetchData.get_datastreams(session,source="google-fit",datatype="com.personicle.individual.datastreams.interval.step.count",start_date=st, end_date=et, is_hard_refresh=true,uid=session[:oktastate]['uid'])
      @response_weight = FetchData.get_datastreams(session,source="google-fit",datatype="com.personicle.individual.datastreams.weight",start_date=st, end_date=et, hard_refresh=true,uid=session[:oktastate]['uid'])
      @response_calories = FetchData.get_datastreams(session,source="google-fit",data_type="com.personicle.individual.datastreams.interval.total_calories",start_date=st, end_date=et, is_hard_refresh=true,user_id=session[:oktastate]['uid'])
     
    else
      puts "not hard refresh"
      @response = FetchData.get_events(session,event_type=false,st,et,hard_refresh=false,uid=session[:oktastate]['uid'])
      @response_step = FetchData.get_datastreams(session,source="google-fit",datatype="com.personicle.individual.datastreams.interval.step.count",start_date=st, end_date=et, hard_refresh=false,uid=session[:oktastate]['uid'])
      @response_weight = FetchData.get_datastreams(session,source="google-fit",datatype="com.personicle.individual.datastreams.weight",start_date=st, end_date=et, hard_refresh=false,uid=session[:oktastate]['uid'])
      @response_calories = FetchData.get_datastreams(session,source="google-fit",data_type="com.personicle.individual.datastreams.interval.total_calories",start_date=st, end_date=et, is_hard_refresh=false,user_id=session[:oktastate]['uid'])

    end 
   
    if !@response.empty?
      # @response = JSON.parse(res,object_class: OpenStruct)
      # last_month_total_sleep, last_month_sleep_events
      # last_week_total_sleep, last_week_sleep_events
      
    respond_to do |format|
      format.html
      format.json { render json: UserEventsDatatable.new(params) }
    end

      @sleep_events = @response.select {|event| event['event_name'] == 'Sleep'}
      # duration is in milliseconds in the data packet
      @last_month_total_sleep = @sleep_events.select {|event| event['start_time'].to_datetime > 30.days.ago}.sum {|event| event['parameters']['duration']}/(60*1000)
      @last_month_sleep_event = @sleep_events.select {|event| event['start_time'].to_datetime > 30.days.ago}.size
      @last_week_total_sleep = @sleep_events.select {|event| event['start_time'].to_datetime > 7.days.ago}.sum {|event| event['parameters']['duration']}/(60*1000)
      @last_week_sleep_event = @sleep_events.select {|event| event['start_time'].to_datetime > 7.days.ago}.size
      
      @last_week_average_sleep = @last_week_sleep_event>0? @last_week_total_sleep/@last_week_sleep_event:0
      @last_month_average_sleep = @last_month_sleep_event>0? @last_month_total_sleep/@last_month_sleep_event:0
      # puts @response
      # puts @last_week_sleep_event
    end

    if !@response_calories.empty?
    
      tmp_calories = @response_calories.select {|record| record['end_time'].to_datetime > 30.days.ago}.map {|rec| [rec['end_time'].to_date, rec['value']]}.group_by {|r| r[0]}.to_h
      @daily_calories = tmp_calories.map {|k,v| [k, v.sum {|r| r[1]}]}.to_h

      @last_month_total_calories = @daily_calories.select {|k,v| k > 30.days.ago}.sum {|k,v| v}
     
      @last_month_calories_days = @daily_calories.select {|k,v| k > 30.days.ago}.size

      @last_week_total_calories = @daily_calories.select {|k,v| k > 7.days.ago}.sum {|k,v| v}
    
      @last_week_calories_days = @daily_calories.select {|k,v| k > 7.days.ago}.size
      

      @last_week_average_calories = @last_week_calories_days>0? @last_week_total_calories/@last_week_calories_days:0
     
      @last_month_average_calories = @last_month_calories_days>0? @last_month_total_calories/@last_month_calories_days:0
     
      
      @response_calories_prev_week = @response_calories.select {|record| record['end_time'].to_datetime > 7.days.ago}.map {|rec| [rec['end_time'].to_date, rec['value']]}.group_by {|r| r[0]}.to_h
     

    end
 

    if !@response_step.empty?
    
      tmp_steps = @response_step.select {|record| record['end_time'].to_datetime > 30.days.ago}.map {|rec| [rec['end_time'].to_date, rec['value']]}.group_by {|r| r[0]}.to_h
      @daily_steps = tmp_steps.map {|k,v| [k, v.sum {|r| r[1]}]}.to_h
      # puts @daily_steps

      @last_month_total_steps = @daily_steps.select {|k,v| k > 30.days.ago}.sum {|k,v| v}
      @last_month_steps_days = @daily_steps.select {|k,v| k > 30.days.ago}.size
      @last_week_total_steps = @daily_steps.select {|k,v| k > 7.days.ago}.sum {|k,v| v}
      @last_week_steps_days = @daily_steps.select {|k,v| k > 7.days.ago}.size

      @last_week_average_steps = @last_week_steps_days>0? @last_week_total_steps/@last_week_steps_days:0
      @last_month_average_steps = @last_month_steps_days>0? @last_month_total_steps/@last_month_steps_days:0
    end

    if !@response_weight.empty?
      #puts @response_weight
      # puts 'Weight Response'
      tmp_weight = @response_weight.group_by_day{|rec| rec['timestamp'].to_datetime}.to_h
      @daily_weight = tmp_weight.map {|k,v| [k, v.sum {|r| r['value']}]}.to_h
      # puts 'Daily Weight'
      # puts @daily_weight
    end

    if Rails.env.production?
      ip = "#{request.ip}"
      results = Geocoder.search(ip)
      # puts results.first.coordinates
      # puts ip
      # @latitude = request.safe_location.latitude
      # @longitude = request.safe_location.longitude
      @latitude =  results.first.coordinates[0]
      @longitude =  results.first.coordinates[1]
      # puts @latitude
      # puts @longitude

      data={
            "individual_id": session[:oktastate]["uid"],
            "streamName": "com.personicle.individual.datastreams.location",
            "source": "PERSONICLE_WEB_APP",
            "dataPoints":[{
              "timestamp": Time.now.getutc,
              "value": [{"latitude": @latitude, "longitude": @longitude}]
            }]
        }

        # puts data.to_json
        res = RestClient::Request.execute(:url => "https://api.personicle.org/data/write/datastream/upload", :payload => data.to_json, :method => :post, headers: {Authorization: "Bearer #{session[:oktastate]['credentials']['token']}", content_type: :json})
           
    end

    # puts @response
  end

  def delete_event
    # url = "https://api.personicle.org/data/write/event/delete"?user_id=userid&event_id=some_event_id;another_event_id
    # RestClient::Request.execute(:url => url, headers: {Authorization: "Bearer #{session[:oktastate]['credentials']['token']} "}, :method => :delete, ),object_class: OpenStruct)
    # params[:select-all] = select-all_value
    events = JSON.parse(params[:selected_events])
   
    
    if !events.nil?
      events = events.join(";") 
      url = "https://staging.personicle.org/data/write/event/delete?user_id=#{session[:oktastate]['uid']}&event_id=#{events}"
      res =  JSON.parse(RestClient::Request.execute(:url => url, headers: {Authorization: "Bearer #{session[:oktastate]['credentials']['token']} "}, :method => :delete,:verify_ssl => false ),object_class: OpenStruct)
      redirect_to pages_dashboard_path, refresh:"hard_refresh"
    end
  end

  def geocode
    
  end
  def update_event
    # Inside update make 2 API calls
    # 1. Delete event api
    # 2. Add events api
      events = JSON.parse(params[:selected_events])
    
    
      if !events.nil?
        events = events.join(";")
        url = "https://api.personicle.org/data/write/event/delete?user_id=#{session[:oktastate]['uid']}&event_id=#{events}"
        res =  JSON.parse(RestClient::Request.execute(:url => url, headers: {Authorization: "Bearer #{session[:oktastate]['credentials']['token']} "}, :method => :delete,:verify_ssl => false ),object_class: OpenStruct)
      end
  
      # ## Get Updated Event
      updated_events = JSON.parse(params[:updated_events])
  
      for index in 0 ... updated_events.size
        # puts "array[#{index}] = #{array[index].inspect}"
        updated_events[index][:individual_id] = session[:oktastate]['uid']
      end
  
      res = RestClient::Request.execute(:url => ENV['EVENT_UPLOAD'], :payload => updated_events.to_json, :method => :post, headers: {Authorization: "Bearer #{session[:oktastate]['credentials']['token']}", content_type: :json})  
      # puts "Params"
      # puts params
      redirect_to pages_dashboard_path, refresh:"hard_refresh"
    end

  def geocode
    
  end

 
end

app/helpers/dashboard_helper.rb
module DashboardHelper

    def random_chartkick_id
        return 'chart-#'+(Random.rand(10000)).to_s
      end
end

app/views/pages/dashboard/charts/_bar.html.erb
<div class="card bg-default">
  <div class="card-header bg-transparent">
    <div class="row align-items-center">
      <div class="col">
        <h6 class="text-uppercase text-muted text-white ls-1 mb-1">Performance</h6>
        <h5 class="h3 text-white mb-0"><span class="hovertext" data-hover="A performance chart indicating the user’s performance in various activities measured in hours."><i class="fa fa-info-circle" aria-hidden="true"></i> Your Summary</h5>
      </div>
    </div>
  </div>
  <div class="card-body">
    <!-- Chart -->
    <div class="chart">
       <% if user_data.length() != 0 %>
      <%# <%= react_component("TimeLine", { user_data: user_data})%> 
      <%= react_component("BarChart", { userSummary: user_data})  %>
    <%else%>
      <h3 style="color:black;"> No activities for the past 3 months</h3>
   <%end%>
       <%# <% if user_data.length() != 0 %>
         <%# <%= react_component("BarChart", { userSummary: user_data}) %>
      <%# <%else%>
        <%# <h3 style="color:white;">No activities for the past 3 months</h3>
      <%end%>   
      <canvas id="chart-bars" class="chart-canvas"></canvas>
    </div>
  </div>
</div>

app/views/pages/dashboard/charts/_physician.html.erb
<style>
.hidden {
    display: none;
}
.tab {
  float: left;
}

</style>
<div class="card">
  <div class="card-header">
    Current Vitals
  </div>
  <div class="row">
    <div class="card-body col-sm-4">
      <h5 class="card-title text-center">Avg 24 Hours Heart Rate</h5>
      <p class="card-text text-center"> <%= avg_24_hour_hr %></p>
 
    </div>
    <div class="card-body col-sm-4">
      <h5 class="card-title text-center">Min 2 Weeks Heart Rate</h5>
      <p class="card-text text-center"><%= last_two_weeks_min_hr %></p>
 
    </div>
    <div class="card-body col-sm-4">
      <h5 class="card-title text-center">Max 2 Weeks Heart Rate</h5>
      <p class="card-text text-center"><%= last_two_weeks_max_hr %> </p>
    </div>
  </div>
</div>
 <div id="chart_type" class="btn-group-vertical btn-group-toggle tab mr-1" data-toggle="buttons">
              <label class="btn btn-secondary">
                <input type="radio" name="charttype" value="sleep_chart" checked> Sleep
              </label>
              <label class="btn btn-secondary">
                <input type="radio" name="charttype" value="activity_chart" > Activity
              </label>
              
              <% if !unique_question_tags.nil? %>
                <% unique_question_tags.each do |tag| %>
                  <label class="btn btn-secondary">
                    <input type="radio" name="charttype" value="<%=tag%>_chart"> <%=tag%>
                  </label>
                <% end %>
              <% end %>
  </div>

<div class="card mr-1" style="width:82%;height:600px">

  <div class="card-header bg-transparent">
    <div class="row align-items-center">
      <div class="col">
        <h6 class="text-black text-uppercase ls-1 mb-1">Overview</h6>
        <h5 class="h3 text-black mb-0">Lifestyle data and trends</h5>
      </div>
      <div class="col">

        <ul  class="nav nav-pills justify-content-end">
          <li class="nav-item mr-2 mr-md-0" value="daily" data-toggle="chart" data-target="#chart-sales-dark" data-update='{"data":{"datasets":[{"data":[0, 20, 10, 30, 15, 40, 20, 60, 60]}]}}' data-prefix="$" data-suffix="k">
          
           <div id="actions" class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary">
                  <input type="radio" name="chart" value="daily" checked> Daily
                </label>
                <label class="btn btn-secondary">
                  <input type="radio" name="chart" value="weekly" > Weekly
                </label>
            </div>
           
          </li>
          <li class="nav-item"  data-toggle="chart" data-target="#chart-sales-dark" data-update='{"data":{"datasets":[{"data":[0, 20, 5, 25, 10, 30, 15, 40, 40]}]}}' data-prefix="$" data-suffix="k">
          </li>
        </ul>
      </div>
    </div>
  </div>
    
  <div class="card-body">
  
    <!-- Chart -->
    <div class="chart">
        
      <div id="charts">
            <%= form_with url: pages_dashboard_physician_get_user_data_path, local: true, method: :post do  %>
                <input type="hidden" name="refresh" value="hard_refresh">
                <input type="hidden" name="data_for_user" value=<%= patient_id %>>
                <button  class="btn btn-primary" type="submit">Refresh</button>
              <% end %>
       
        <% if !user_data.nil? %>
          <% if user_data.length() != 0 or user_events.length()!=0 or !patient_responses.nil?  %>
          <% 
            @numeric_responses =  patient_responses.filter {|rec| rec[0][3] == "numeric"}.group_by {|rec| rec[0][1]}

            
            # puts @numeric_responses
          %>
        <% unique_question_tags.each do |tag|%>
          <div id="<%=tag%>_chart_daily" class="chart hidden">
           <%
              @patient_responses=  patient_responses.filter {|rec| rec[0][0] == tag}.group_by {|rec| rec[0][1]}
              numeric_responses = []
              avg_numeric_responses=[]
              @numeric_responses_data = []
              show_numeric_chart = false
              show_image_chart = false

          
                 @data = []
                 @patient_responses.each do |k,v|

                  numeric_responses = v.filter {|r| r[0][3] == "numeric"}.group_by {|rec| rec[0][1]}
                  image_responses = v.filter {|r| r[0][3] == "image"}.group_by {|rec| rec[0][1]}
                  avg_numeric_responses = numeric_responses.map {|k,v|  [k, v.sum {|r| r[1] * r[0][2].to_i}/v.sum{ |r| r[1]}] }
                  if !avg_numeric_responses.empty?
                      avg_numeric_responses.each do |k,v|
                        @numeric_responses_data.push(
                          [k,v] 
                        )
                       end
                    show_numeric_chart = true
                  elsif !image_responses.empty?
                    show_image_chart = true 
                  else
                      v.each do |key,val|
                        @data.push({
                          name: key[2], data: [ [k,val] ]
                        })
                      end
                  end
                 end
           %> 
            
               <% if show_numeric_chart == true %> 
                <%# <% puts @numeric_responses_data %>
                <%# <% puts @data %> 

                <%= line_chart  @numeric_responses_data,points:false, title: tag, round: 2, loading: "Loading...",
                    xtitle: "", ytitle: ""
                  %>
                <% elsif show_image_chart == true%>
                  <%= react_component("ImageVisualization", {user_id: user_id, image_urls: image_urls, tag: tag, auth: session[:oktastate]['credentials']['token']}) %>
              <% else %> 
                <%# <% puts @data %>  
                  <%= column_chart  @data, title: tag, library: { isStacked: 'percent' },suffix: "",points:false, round: 2, loading: "Loading...", xtitle: "Date", ytitle: "Total Responses", stacked: true %>  
                <%end%>  
          </div>

          <div id="<%=tag%>_chart_weekly" class="chart hidden">
           <%
              @patient_responses=  patient_responses.filter {|rec| rec[0][0] == tag}.group_by {|rec| rec[0][1].strftime('%Y-%U')}
              @data = []
                 @patient_responses.each do |k,v|
                      v.each do |key,val|
                        @data.push({
                          name: key[2], data: [ [k,val] ]
                        })
                        
                      end
                 end
           %> 
           <%= column_chart  @data,   title: tag, library: { isStacked: 'percent' },suffix: "",points:false, round: 2, loading: "Loading...", xtitle: "Year - Week number", ytitle: "Total Responses", stacked: true %>
          </div>
        <%end%>
        <div id="activity_chart_daily" class="chart hidden">

            <%= column_chart [
                  {
                      name: "Daily Steps", type: "column", data: daily_step_summary
                  }
              ], suffix: " steps",points:false, round: 2, loading: "Loading...", xtitle: "Date", ytitle: "Total Steps" %> 
        </div>

        <div id="activity_chart_weekly" class="chart hidden">

            <%= column_chart [
                  {
                      name: "Weekly Steps", type: "column", data: weekly_step_summary
                  }
              ], suffix: " steps",points:false, round: 2, loading: "Loading...", xtitle: "Year - Week number", ytitle: "Total Steps" %>

        </div>

        <div id="sleep_chart_daily" class="chart">
          
            <%= column_chart [
                  {
                      name: "Daily Sleep", type: "column", data: daily_sleep_summary.map {|k,v| [k, v['duration']]} 
                  }
              ], suffix: " h",points:false, round: 2, loading: "Loading...", xtitle: "Date", ytitle: "Sleep Duration (hours)" %>

        </div>
          <div id="sleep_chart_weekly"  class="chart hidden">
                <%= column_chart [
                    {
                        name: "Weekly Sleep", type: "column", data: weekly_sleep_summary
                    }
                ], suffix: " h",points:false, round: 2, loading: "Loading...", xtitle: "Year - Week number", ytitle: "Sleep Duration (hours)" %> 
            
          </div>
      </div> 
          
      <%else%>
        <h3 style="color:black;">No activities for the past 3 months</h3>
      <%end%>
      <%end%>

     
      <%# <canvas id="chart-sales-dark" class="chart-canvas"></canvas> %>
    </div>
        
  </div>
</div>
<script>

function revealChartType(event) {
    var chart_type = $(event.target).val(); 
    var chart = $('input[name="chart"]:checked').val();
    $('#charts .chart').hide(); 
    $('#' + chart_type +"_"+chart).show();  
}
$(function() {
    $('#chart_type input').click(revealChartType);
});

// to reveal daily or weekly chart
function revealChart(event) {
    var chart = $(event.target).val(); 
    var chart_type = $('input[name="charttype"]:checked').val();
    $('#charts .chart').hide(); 
    $('#' + chart_type +"_"+chart).show();  
}
$(function() {
    $('#actions input').click(revealChart);
});
</script>

app/views/pages/dashboard/charts/_weight.html.erb
<div class="card">
  <div class="card-header bg-transparent">
    <div class="row align-items-center">
      <div class="col">
        <h5 class="h3 text-black mb-0"><span class="hovertext" data-hover="A line chart showing user’s weight in kg by date."><i class="fa fa-info-circle" aria-hidden="true"></i></span> Your Weight</h5>
    <!-- Chart -->
      </div>
    </div>
  </div>
  <div class="card-body">
    <div class="chart">
        
      <% if user_weight.length() != 0 %>
         
      <div id="charts">
          
        <div id="weight_chart_daily" class="chart hidden">

            <%= line_chart [
                  {
                      name: "Daily Weight", type: "line", data: user_weight
                  }
              ], suffix: " kg",points:true, round: 2, loading: "Loading...", xtitle: "Date", ytitle: "Total Weight" %>

        </div>
          
      <%else%>
        <h3 style="color:black;">No activities for the past 3 months</h3>
      <%end%>
     
      <%# <canvas id="chart-sales-dark" class="chart-canvas"></canvas> %>
    </div>
        
  </div>
  </div>