config/routes.rb
Rails.application.routes.draw do
  
  get 'mobility/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'home/index'
  
  # devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/logout', :to => 'sessions#destroy'
  get '/login', :to => 'sessions#new', :as => :login
  resources :users
  root to: 'pages#login'
  get 'pages/dashboard', :to => 'dashboard#index'
  get 'pages/dashboard/physician', :to =>'physician#index'
  # post 'pages/physician-create-account', :to =>'physician#create_account'
  post 'pages/dashboard', :to => 'dashboard#index'
  get 'pages/connections', :to => 'connection#index'
  get 'pages/profile', :to => 'profile#index'
  post 'pages/profile/add_physician', :to=>'profile#add_physician'
  post 'pages/profile/update_user_info', :to=>'profile#update_user_info'
  # post 'pages/profile', :to => 'profile#index'
  get 'pages/foodlog', :to => 'foodlog#index'
  get 'pages/foodlog/data', :to => 'foodlog#get_edamam_data' , :as => 'get_edamam_data' 
  post 'pages/foodlog/log', :to => 'foodlog#log_food', :as => 'log_food'
  get 'pages/mobility', :to => 'mobility#index'
  post 'pages/mobility', :to => 'mobility#index'
  get 'pages/sleep', :to => 'sleep#index'
  post 'pages/sleep', :to => 'sleep#index'
  # get 'pages/foodlog/recipes', :to => 'foodlog#render'
  get 'pages/login'
  post 'pages/create-physician-account', :to => 'pages#create_physician_account'
  # get 'pages/register'
  # get 'pages/recipes'
  get 'pages/dashboard/physician-questions', :to=> 'user_questions#index'
  post 'pages/dashboard/physician-questions', :to=> 'user_questions#send_responses'
  post 'pages/profile/remove_physician', :to=>'profile#remove_physician'
  post 'pages/dashboard/physician/get_user_data',  :to =>'physician#get_user_data'
  get  'pages/dashboard/physician/get_user_data',  :to =>'physician#get_user_data'
  post 'question/create', :to => 'question#create'
  post 'question/delete', :to => 'question#delete_questions'
  get  'image/upload', :to => 'image#upload'
  post 'image/send_packet', :to => 'image#send_packet', :as => 'send_packet'
  post 'image/delete', :to => 'image#delete_image', :as => 'delete_image'

  post 'pages/dashboard/delete-event', :to => 'dashboard#delete_event', :as => 'delete_user_events'
  post 'pages/dashboard/update-event', :to => 'dashboard#update_event', :as => 'update_user_events'
  get 'pages/exposome', :to => 'exposome#index'
  post 'pages/exposome', :to => 'exposome#index'
  get 'pages/exposome/get_exposome_data', :to => 'exposome#get_exposome_data', :as => 'get_exposome_data'

  get 'pages/user/create_question', :to => 'create_user_questions#index'
  post 'pages/user/create_question', :to => 'create_user_questions#create'
  delete 'pages/user/create_question',  :to => 'create_user_questions#destroy'

  post 'pages/user/send_responses', :to => 'create_user_questions#send_responses'
  get 'pages/user/responses', :to => 'user_responses#index'
  post 'pages/user/responses', :to => 'user_responses#index'

  get 'pages/notifications', :to => 'notification#index'
  post 'pages/notifications/mark_notification_as_read', :to => 'notification#mark_notification_as_read'
  get 'pages/dashboard', to: 'dashboard#geocode'
  get 'physician/questions', :to=> 'user_questions#get_physicians_questions'
  get 'api/physicians', :to=> 'physicians_api#get_users_physicians' #  get physicians for a user
  get 'api/physicians/all', :to=> 'physicians_api#get_all_physicians' #  get  all physicians
  
  get 'api/physician/:id', :to=> 'physicians_api#get_physician' # get specific physician
  post 'api/update/user', :to=> 'profile#update_user'   # update user profile
  get 'api/user', :to=> 'profile#get_user'    # get specific user
  post 'api/user/physicians', :to=> 'profile#add_physicians_api' #  add physicians to user
  # get 'api/user/physicians', :to=> 'profile#get_users_physicians_api' #  get users physicians
  post 'api/user/physicians/remove', :to=> 'profile#remove_physicinas_api' #  remove user physicians
  
  get 'pages/mobility/last_month', to: 'mobility#last_month' #get last month's mobility data
  # get 'pages/mobility/last_week', to: 'mobility#last_week', as: 'last_week' 
  # post 'pages/mobility/last_week', to: 'mobility#last_week', as: 'last_week' 

  get 'pages/mobility/pick_date', to: 'mobility#pick_date', as: 'pick_date' #get path to pick_date from the _bar_totalsteps_dayandweek.html.erb 
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :require_user, only: [:remove_physician, :add_physician,:update_user_info ,:index]
  before_action :session_active?, only: [:remove_physician, :add_physician,:update_user_info ,:index]
  before_action :get_user_notifications, only: [:remove_physician, :add_physician,:update_user_info ,:index]
  protect_from_forgery with: :null_session
  # before_action :require_user, :session_active?, :get_user_notifications
    def remove_physician
      if not params[:remove_physicians].blank? and !session[:oktastate]["physician"]
        @user = User.find_by(user_id: session[:oktastate]["uid"])
        params[:remove_physicians].each do |phy|
          @phy = Physician.find_by(user_id: phy)
          @user.physicians.destroy(@phy)
        end
        flash[:warning] = "Successfully removed physicians"
        redirect_to pages_profile_path
      end
    end

    def add_physician
      puts "hello"
      if not params[:physicians].blank? and !session[:oktastate]["physician"]
        @user = User.find_by(user_id: session[:oktastate]["uid"])
        
        params[:physicians].each do |phy|
          @phy = Physician.find_by(user_id: phy)
          puts"hello"
          @user.physicians << @phy
        end
        flash[:success] = "Successfully added physicians"
        redirect_to pages_profile_path
      end

    end

    def update_user_info
      puts params.except(:authenticity_token, :action, :controller)
      @user = User.find_by(user_id: session[:oktastate]['uid'])
      payload = {}
      params.except(:authenticity_token, :action, :controller).each do |k,v|
        if !v.blank?
          payload[k] =  v
        end
      end

      payload.each do |k,v|
        @user.info[k] = v
      end
      @user.save
      return redirect_to pages_profile_path
    end


    # api endpoint to remove physicians from user
    def remove_physicinas_api
      begin
        res = JSON.parse(RestClient::Request.execute(:url => "https://api.personicle.org/auth/authenticate", headers: {Authorization: request.authorization}, :method => :get ),object_class: OpenStruct)
        @user = User.find_by(user_id: res['user_id'])
        params[:physicians].each do |phy|
          @phy = Physician.find_by(user_id: phy)
          @user.physicians.destroy(@phy)
        end
        render json: {message: 'Successfully removed physicians'}, status: 200
      rescue => exception
        if exception.response.code == 401
          return  render status: :unauthorized, json: { error: "Unauthorized. You are not authorized to access this resource." }
        end
      end
    end
    
    def get_users_physicians_api
      begin
        res = JSON.parse(RestClient::Request.execute(:url => "https://api.personicle.org/auth/authenticate", headers: {Authorization: request.authorization}, :method => :get ),object_class: OpenStruct)
        @user = User.find_by(user_id: res['user_id'])
        @phys = @user.physicians
      rescue => exception
        
      end
    end

    # api endpoint to add physicians for a user
    def add_physicians_api
      begin
        res = JSON.parse(RestClient::Request.execute(:url => "https://api.personicle.org/auth/authenticate", headers: {Authorization: request.authorization}, :method => :get ),object_class: OpenStruct)
        @user = User.find_by(user_id: res['user_id'])
        params[:physicians].each do |phy|
          @phy = Physician.find_by(user_id: phy)
          @user.physicians << @phy
        end
        render json: {message: 'Successfully added physicians'}, status: 200
      rescue => exception
        if exception.response.code == 401
          return  render status: :unauthorized, json: { error: "Unauthorized. You are not authorized to access this resource." }
        end
      end
    end

   # api endpoint  to update user info 
    def update_user
      begin
        res = JSON.parse(RestClient::Request.execute(:url => "https://api.personicle.org/auth/authenticate", headers: {Authorization: request.authorization}, :method => :get ),object_class: OpenStruct)
        @user = User.find_by(user_id: res['user_id'])
        payload = {}
        params.each do |k,v|
          if !v.blank?
            payload[k] =  v
          end
        end
  
        payload.each do |k,v|
          @user.info[k] = v
        end
        @user.save
        render json: {}, status: 200
      rescue => exception
        if exception.response.code == 401
            return  render status: :unauthorized, json: { error: "Unauthorized. You are not authorized to access this resource." }
        end
      end
    end



    def get_user_profile_image
      @user = User.find_by(user_id: session[:oktastate]["uid"])
      # get user profile image 
      image_key = @user.info['image_key']
      if !image_key.nil?
        res = JSON.parse(RestClient::Request.execute(:url => "http://personicle-file-upload.herokuapp.com/user_images/#{image_key}?user_id=#{session[:oktastate]['uid']}", headers: {Authorization: "Bearer #{session[:oktastate]['credentials']['token']} "}, :method => :get,:verify_ssl => false ),object_class: OpenStruct)
        # puts res['image_url']
      
        return res['image_url']
      else
        return  nil
      end
    end
    
    def get_user
      begin
        res = JSON.parse(RestClient::Request.execute(:url => "https://api.personicle.org/auth/authenticate", headers: {Authorization: request.authorization}, :method => :get ),object_class: OpenStruct)
        @user = User.find_by(user_id: res['user_id'])
        return  render json: @user.to_json(), status: 200
      rescue => exception
        if exception.response.code == 401
          return  render status: :unauthorized, json: { error: "Unauthorized. You are not authorized to access this resource." }
        end
      end
    end

    def index
      
      # if session[:oktastate]["physician"] and not params[:users].blank?
      #   redirect_to "https://personicle-physician.herokuapp.com/?auth=#{session[:oktastate]['credentials']['token']}&patient_id=#{params[:users]}", :target => "_blank" 

      # end

      if not params[:delete_account].blank? and params[:delete_account] == "delete"
        url = ENV['ACCOUNT_DELETE']
       
        print(res.code)
        print(res)
        if res.code == 200
          session[:oktastate] = nil
          flash[:warning] = "Your account is successfully deleted"
          redirect_to root_path
        end
      end

      if !session[:oktastate]["physician"]
        
        @profile_image_url = get_user_profile_image()
      else
        @physician = Physician.find_by(user_id: session[:oktastate]["uid"])
        @profile_image_url = get_user_profile_image()
      end

    end
  end
  

app/views/pages/profile/_edit_card.html.erb
<div class="card">
<%# <%= render 'layouts/messages' %> 
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col-8">
        <h3 class="mb-0">Edit profile </h3>
      </div>
      <div class="col-4 text-right">
        <a href="#!" class="btn btn-sm btn-primary">Settings</a>
      </div>
    </div>
  </div>
  <div class="card-body">
    <%= form_with url: pages_profile_update_user_info_path, local: true, method: :post do  %>
      <h6 class="heading-small text-muted mb-4">User information</h6>
      <% @user = User.find_by(user_id: session[:oktastate]['uid'])%>
      
      <div class="pl-lg-4">
        <div class="row">
          <div class="col-lg-6">
            <%# <div class="form-group">
              <label class="form-control-label" for="input-username">Username</label>
              <input type="text" id="input-username" class="form-control" placeholder="Username" value="">
            </div> %>
          </div>
          <div class="col-lg-6">
            <%# <div class="form-group">
              <label class="form-control-label" for="input-email">Email address</label>
              <input type="email" id="input-email" class="form-control" placeholder="<%= session[:oktastate]["info"]["email"]%>
            <%# </div> %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <%# <div class="form-group">
              <label class="form-control-label" for="input-first-name">First name</label>
              <input type="text" id="input-first-name" class="form-control" placeholder="First name" value="<%= session[:oktastate]["info"]["first_name"]%>
            <%# </div> %> 
          </div>
          <div class="col-lg-6">
            <%# <div class="form-group">
              <label class="form-control-label" for="input-last-name">Last name</label>
              <input type="text" id="input-last-name" class="form-control" placeholder="Last name" value="<%= session[:oktastate]["info"]["last_name"]%>
            <%# </div> %>
          </div>
        </div>
         <div class="row">
          <div class="col-lg-6">
            <div class="form-group">

              <label class="form-control-label" for="input-dob">Date of Birth</label>
             <input type="date" id="input-dob" class="form-control"  max="<%= Time.now.strftime("%Y-%m-%d")%>" value="<%= !@user.info['dob'].nil? ? @user.info['dob'] : '' %>" name="dob" onload="getDate()">
            </div>
          </div>
          </div>
        <div class="row">
          <div class="col-lg-6">
            <div class="form-group">

             <label class="form-control-label" for="input-height">Height</label>
              <div class="input-group mb-3">
                  
                      <input type="text" id="input-height" class="form-control" placeholder="<%= !@user.info['height'].nil? ? @user.info['height'] : 'Enter height' %>" name="height">
                  <div class="input-group-append">
                    <span class="input-group-text">cm</span>
                  </div>
              </div>
          
            
            
            </div>
          </div>
          <div class="col-lg-6">
            <div class="form-group">
            <label class="form-control-label" for="input-weight">Weight</label>
              <div class="input-group mb-3">
                  
                <input type="text" id="input-weight" class="form-control" placeholder="<%= !@user.info['weight'].nil? ? @user.info['weight'] : 'Enter weight' %>" name="weight">
                    <div class="input-group-append">
                    <span class="input-group-text">lb</span>
                  </div>
              </div>
              
            </div>
          </div>
        </div>
      </div>
      <hr class="my-4" />
      <!-- Address -->
      <h6 class="heading-small text-muted mb-4">Contact information</h6>
      <div class="pl-lg-4">
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <label class="form-control-label" for="input-address">Address</label>
              <input id="input-address" class="form-control" placeholder="<%= !@user.info['address'].nil? ? @user.info['address'] : 'Home Address' %>" name="address" type="text">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4">
            <div class="form-group">
              <label class="form-control-label" for="input-city">City</label>
              <input type="text" id="input-city" class="form-control" placeholder="<%= !@user.info['city'].nil? ? @user.info['city'] : 'Your City' %>"  name="city">
            </div>
          </div>
          <div class="col-lg-4">
            <div class="form-group">
              <label class="form-control-label" for="input-country">Country</label>
              <input type="text" id="input-country" class="form-control" placeholder="<%= !@user.info['country'].nil? ? @user.info['country'] : 'Your Country' %>" name="country">
            </div>
          </div>
          <div class="col-lg-4">
            <div class="form-group">
              <label class="form-control-label" for="input-country">Postal code</label>
              <input type="number" id="input-postal-code" class="form-control" name="zipcode" placeholder="<%= !@user.info['zipcode'].nil? ? @user.info['zipcode'] : 'Your Zipcode' %>" >
            </div>
          </div>
        </div>
      </div>
      <hr class="my-4" />
      <!-- Description -->
      <h6 class="heading-small text-muted mb-4">About me</h6>
      <div class="pl-lg-4">
        <div class="form-group">
          <label class="form-control-label">About Me</label>
          <textarea rows="4" class="form-control" placeholder="A few words about you ..."></textarea>
        </div>
      </div>
      <button type="submit" class="btn btn-primary mt-1">Update</button>
    <% end %>


    <% if !session[:oktastate]["physician"]%>
     
      <div class="pl-lg-4">
        <div class="row">
            <div class="col-lg-6">
             <h6 class="heading-small text-muted mb-4"><span class="hovertext" data-hover="Enables the user to click a Physician and click 'Add' to add to user's list of Physicians."><i class="fa fa-info-circle" aria-hidden="true"></i> Add physicians</h6></span>
              <% @physicians = Physician.all %>
              <%= form_with url: pages_profile_add_physician_path, local: true, method: :post do  %>
                  <select name="physicians[]" multiple>
                        <% @physicians.each do |phy| %>
                        <%# <% if !@user.physicians.exists?(phy.user_id)%> 
                              <option value=<%= phy.user_id %> > <%=phy.name%> </option>
                        <%# <% end %> 
                        <% end %>   
                  </select>
                  <br>
                  <button type="submit" class="btn btn-primary mt-3">Add</button>
              <% end %>
            </div>   
            <div class="col-lg-6">
        
                <%# <label class="form-control-label" for="input-address">Your Physicians</label> %>
              <h6 class="heading-small text-muted "><span class="hovertext" data-hover="Enables the user to click a Physician and click 'Remove' to remove a Physician from user's list of Physicians."><i class="fa fa-info-circle" aria-hidden="true"></i> Your physicians</h6></span>
              <%= form_with url: pages_profile_remove_physician_path, local: true, method: :post do  %>
              <select name="remove_physicians[]" multiple>
                  <% @user.physicians.each do |phy| %>
                      <option value=<%= phy.user_id %> > <%=phy.name%> </option>
                  <% end %>   
              </select>
                  <br>
                  <button type="submit" class="btn btn-warning mt-3">Remove</button>
              <% end %>
            
            </div>
          </div>
        </div>

    <% end %>
    <% if false %>
    <% if session[:oktastate]["physician"]%>
      <h6 class="heading-small text-muted mb-4">Your Patients</h6>
      <div class="pl-lg-4">
      <div class="row">
          <div class="col-lg-6">
            <%= form_with url: pages_profile_path, method: :get do  %>
                <select name="users" >
                      <% @physician.users.each do |u| %>
                        <option value=<%= u.user_id %> > <%=u.name%>, <%=u.email%> </option>
                      <% end %>   
                </select>
            <br>
            <button class="btn btn-primary mt-3">View selected patient's data</button>
            <% end %>
            </div>   
    <% end %>
     <% end %>
          <%# <div class="col-lg-6">
            <div class="form-group">
              <label class="form-control-label" for="input-email">Email address</label>
              <input type="email" id="input-email" class="form-control" placeholder="<%= session[:oktastate]["info"]["email"]%>
            <%# </div>
          </div> %> 
        </div>
        <%# <div class="row"> %>
          <%# <div class="col-lg-6"> %>
            <%# <div class="form-group">
              <label class="form-control-label" for="input-username">Username</label>
              <input type="text" id="input-username" class="form-control" placeholder="Username" value="">
            </div> %>
          <%# </div> %>
          <%# <div class="col-lg-6">
            <div class="form-group">
              <label class="form-control-label" for="input-email">Email address</label>
              <input type="email" id="input-email" class="form-control" placeholder="<%= session[:oktastate]["info"]["email"]%>
            <%# </div>
          </div> %>
        <%# </div> %>
        
          
      <!-- Address -->
      
      </div>
      
      <!-- Description -->
      
 
  </div>
  
</div>
<script>

function getDate(){
    var today = new Date();
    document.getElementById("date").value = today.getFullYear() + '-' + ('0' + (today.getMonth() + 1)).slice(-2) + '-' + ('0' + today.getDate()).slice(-2);

}
</script>

app/views/pages/profile/_header.html.erb
<div id="profile-header" class="header pb-6 d-flex align-items-center">
  <!-- Mask -->
  <span class="mask bg-gradient-default opacity-8"></span>
  <div class="container-fluid d-flex align-items-center">
    <div class="row">
      <div class="col-lg-7 col-md-10">
        <h1 class="display-2 text-white">Hello <%= session[:oktastate]["info"]["first_name"] %></h1>
        <p class="text-white mt-0 mb-5">This is your profile page. You can see edit your profile here.</p>
        <%# <a href="#!" class="btn btn-neutral">Edit profile</a> %>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile/_physician_user.html.erb
<div class="card card-profile">
  <%= image_tag "theme/img-1-1000x600.jpg", class: "card-img-top", alt: "Image placeholder" %>
  <div class="row justify-content-center">
    <div class="col-lg-3 order-lg-2">
      <div class="card-profile-image">
        <a >
          <%= image_tag 'theme/sketch2.jpg', class: 'rounded-circle' %>
        </a>
      </div>
    </div>
  </div>
  <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
    <%# <div class="d-flex justify-content-between">
      <a href="#" class="btn btn-sm btn-info  mr-4 ">Connect</a>
      <a href="#" class="btn btn-sm btn-default float-right">Message</a>
    </div> %>
  </div>
  <div class="card-body pt-0 ">
    <div class="text-center mt-4">
    <% @user = User.find_by(user_id: patient_id) %>
      <h5 class="h3">
        <%= @user.name %><span class="font-weight-light"></span>
      </h5>
   </div>
   
    
     <div class="row">
            <div class="col-md-12">Age: <b><%= !@user.info['age'].nil? ? @user.info['age'] : '' %></b></div>
    </div> 
    <div class="row">
            <div class="col-md-12"> Weight: <b><%= !@user.info['weight'].nil? ?  @user.info['weight'] : '' %></b></div>
    </div> 
    <div class="row">
            <div class="col-md-12">Height: <b><%= !@user.info['height'].nil? ?  @user.info['height'] : ''%></b></div>
    </div> 
    
     <div class="row">
            <div class="col-md-12">Zipcode: <b><%= !@user.info['zipcode'].nil? ? @user.info['zipcode'] : ''%></b></div>
    </div>
    
  </div>
</div>

app/views/pages/profile/_summary_card.html.erb
<div class="card card-profile">
  <%= image_tag "theme/img-1-1000x600.jpg", class: "card-img-top", alt: "Image placeholder" %>
  <div class="row justify-content-center">
    <div class="col-lg-3 order-lg-2">
      <div class="card-profile-image">
        <%# <a href="#"> %>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        <% if !profile_image_url.nil?%>
           <%= image_tag  profile_image_url, class: 'rounded-circle' %>
        <% else %>
          <%= image_tag  'theme/sketch.jpg', class: 'rounded-circle' %>
        <% end %>
        </button>
        
        <%# </a> %>
      </div>
    </div>
  </div>
  <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
    <div class="d-flex justify-content-between">
      <%# <a href="#" class="btn btn-sm btn-info  mr-4 ">Connect</a>
      <a href="#" class="btn btn-sm btn-default float-right">Message</a> %>
    </div>
  </div>
  <div class="card-body pt-0">
    <div class="row">
      <div class="col">
        <div class="card-profile-stats d-flex justify-content-center">
          <%# <div>
            <span class="heading">22</span>
            <span class="description">Friends</span>
          </div>
          <div>
            <span class="heading">10</span>
            <span class="description">Photos</span>
          </div>
          <div>
            <span class="heading">89</span>
            <span class="description">Comments</span>
          </div> %>
        </div>
      </div>
    </div>
    <div class="modal fade" id="deleteAccountModal" tabindex="-1" role="dialog" aria-labelledby="deleteAccountLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete your Personicle account?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your personicle account? <br>
        All your data will be deleted from personicle servers.
      </div>
      <%= form_with url: pages_profile_path, local: true, method: :post do  %>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" name="delete_account" value="delete" class="btn btn-danger">Delete my account</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

    <div class="text-center">
      <h5 class="h3">
        <%= session[:oktastate]["info"]["name"]%><span class="font-weight-light"></span>
   
      </h5>
      <div class="h5 font-weight-300">
           <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteAccountModal">
               Delete Account
           </button>

        <%# <i class="ni location_pin mr-2"></i>Bucharest, Romania %>
      </div>
      <div class="h5 mt-4">
        <%# <i class="ni business_briefcase-24 mr-2"></i>Solution Manager - Creative Tim Officer %>
      </div>
      <div>
        <%# <i class="ni education_hat mr-2"></i>University of Computer Science %>
      </div>
    </div>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Profile Image</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form  id="upload-profile-image">
      <div class="modal-body">
          <div class="spinner-border text-primary" 
            id="spinner-profile-image-upload" role="status" style="margin:0 auto;display:none;">
            <span class="sr-only">Loading...</span>
          </div>
          <fieldset class="my-2">
            <input
              type="file"
              name="image"
              id="image"
              class="w-full block p-3"
              placeholder="image"
              onchange="readURL(this);"
            />
              <img id="uploadedimge" src="#" alt="your image" />
          </fieldset>
           <input
            type="hidden"
            name="individual_id"
            id="individual_id"
            class="w-full block p-3 shadow-sm"
            placeholder="Individual Id"
            value = "<%= session[:oktastate]['uid']%>"
        
           />
           <input
            type="hidden"
            name="session"
            id="session"
            class="w-full block p-3 shadow-sm"
            value = "<%= session[:oktastate]['credentials']['token']%>"
          />
      </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </form>
    </div>
  </div>
</div>
<script>
 function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#uploadedimge')
                .attr('src', e.target.result)
                .width(150)
                .height(200);
        };
        reader.readAsDataURL(input.files[0]);
    }
}

async function uploadProfileImage(form,formData) {
  document.getElementById('spinner-profile-image-upload').style.display = 'block';
	const response = await fetch(
		'https://personicle-file-upload.herokuapp.com/user_images',
    // 'http://localhost:3001/user_images',
		{
			method: 'post',
      body: formData,
			headers: {
		      'Authorization': `Bearer ${form.session.value}`
			}
		}
	);
  if (response){
    document.getElementById('spinner-profile-image-upload').style.display = 'none';
  }
  // if (await response){
  //   console.log("hello")
  //   document.getElementById('spinner').style.display = 'none';
  // }
	if (!response.ok) {
		// throw new Error(`HTTP error! status: ${response.status}`);
    	const data = await response.json();
      alert(data)
      return
	}
	const data = await response.json();
  let payload= {}
  data.forEach(function(image){
    payload["image_key"] = image.image_key // payload to update user info (image_key) 
   });
 $.ajax({
      type: "POST",
      url: "/pages/profile/update_user_info",
      data : payload
    });
}
const form = document.getElementById('upload-profile-image');
form.addEventListener('submit', (e) => {
       e.preventDefault()
        const form = e.target
        const formData = new FormData()
        formData.append('user_image[individual_id]', form.individual_id.value)
        for (let i = 0; i < form.image.files.length; i++) {
          formData.append(
            'user_image[images][]',
            form.image.files[i],
            form.image.files[i].name
          )
        }
        uploadProfileImage(form,formData)
});
 document.getElementById('spinner-profile-image-upload').style.display = 'none';
</script>