config/routes.rb
Rails.application.routes.draw do
  
  get 'mobility/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'home/index'
  
  # devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/logout', :to => 'sessions#destroy'
  get '/login', :to => 'sessions#new', :as => :login
  resources :users
  root to: 'pages#login'
  get 'pages/dashboard', :to => 'dashboard#index'
  get 'pages/dashboard/physician', :to =>'physician#index'
  # post 'pages/physician-create-account', :to =>'physician#create_account'
  post 'pages/dashboard', :to => 'dashboard#index'
  get 'pages/connections', :to => 'connection#index'
  get 'pages/profile', :to => 'profile#index'
  post 'pages/profile/add_physician', :to=>'profile#add_physician'
  post 'pages/profile/update_user_info', :to=>'profile#update_user_info'
  # post 'pages/profile', :to => 'profile#index'
  get 'pages/foodlog', :to => 'foodlog#index'
  get 'pages/foodlog/data', :to => 'foodlog#get_edamam_data' , :as => 'get_edamam_data' 
  post 'pages/foodlog/log', :to => 'foodlog#log_food', :as => 'log_food'
  get 'pages/mobility', :to => 'mobility#index'
  post 'pages/mobility', :to => 'mobility#index'
  get 'pages/sleep', :to => 'sleep#index'
  post 'pages/sleep', :to => 'sleep#index'
  # get 'pages/foodlog/recipes', :to => 'foodlog#render'
  get 'pages/login'
  post 'pages/create-physician-account', :to => 'pages#create_physician_account'
  # get 'pages/register'
  # get 'pages/recipes'
  get 'pages/dashboard/physician-questions', :to=> 'user_questions#index'
  post 'pages/dashboard/physician-questions', :to=> 'user_questions#send_responses'
  post 'pages/profile/remove_physician', :to=>'profile#remove_physician'
  post 'pages/dashboard/physician/get_user_data',  :to =>'physician#get_user_data'
  get  'pages/dashboard/physician/get_user_data',  :to =>'physician#get_user_data'
  post 'question/create', :to => 'question#create'
  post 'question/delete', :to => 'question#delete_questions'
  get  'image/upload', :to => 'image#upload'
  post 'image/send_packet', :to => 'image#send_packet', :as => 'send_packet'
  post 'image/delete', :to => 'image#delete_image', :as => 'delete_image'

  post 'pages/dashboard/delete-event', :to => 'dashboard#delete_event', :as => 'delete_user_events'
  post 'pages/dashboard/update-event', :to => 'dashboard#update_event', :as => 'update_user_events'
  get 'pages/exposome', :to => 'exposome#index'
  post 'pages/exposome', :to => 'exposome#index'
  get 'pages/exposome/get_exposome_data', :to => 'exposome#get_exposome_data', :as => 'get_exposome_data'

  get 'pages/user/create_question', :to => 'create_user_questions#index'
  post 'pages/user/create_question', :to => 'create_user_questions#create'
  delete 'pages/user/create_question',  :to => 'create_user_questions#destroy'

  post 'pages/user/send_responses', :to => 'create_user_questions#send_responses'
  get 'pages/user/responses', :to => 'user_responses#index'
  post 'pages/user/responses', :to => 'user_responses#index'

  get 'pages/notifications', :to => 'notification#index'
  post 'pages/notifications/mark_notification_as_read', :to => 'notification#mark_notification_as_read'
  get 'pages/dashboard', to: 'dashboard#geocode'
  get 'physician/questions', :to=> 'user_questions#get_physicians_questions'
  get 'api/physicians', :to=> 'physicians_api#get_users_physicians' #  get physicians for a user
  get 'api/physicians/all', :to=> 'physicians_api#get_all_physicians' #  get  all physicians
  
  get 'api/physician/:id', :to=> 'physicians_api#get_physician' # get specific physician
  post 'api/update/user', :to=> 'profile#update_user'   # update user profile
  get 'api/user', :to=> 'profile#get_user'    # get specific user
  post 'api/user/physicians', :to=> 'profile#add_physicians_api' #  add physicians to user
  # get 'api/user/physicians', :to=> 'profile#get_users_physicians_api' #  get users physicians
  post 'api/user/physicians/remove', :to=> 'profile#remove_physicinas_api' #  remove user physicians
  
  get 'pages/mobility/last_month', to: 'mobility#last_month' #get last month's mobility data
  # get 'pages/mobility/last_week', to: 'mobility#last_week', as: 'last_week' 
  # post 'pages/mobility/last_week', to: 'mobility#last_week', as: 'last_week' 

  get 'pages/mobility/pick_date', to: 'mobility#pick_date', as: 'pick_date' #get path to pick_date from the _bar_totalsteps_dayandweek.html.erb 
end

app/views/pages/tables/_avatar_group.html.erb
<div class="avatar-group">
  <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Ryan Tompson">
    <%= image_tag "theme/team-1.jpg", alt: "..." %>
  </a>
  <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Romina Hadid">
    <%= image_tag "theme/team-2.jpg", alt: "..." %>
  </a>
  <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Alexander Smith">
    <%= image_tag "theme/team-3.jpg", alt: "..." %>
  </a>
  <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Jessica Doe">
    <%= image_tag "theme/team-4.jpg", alt: "..." %>
  </a>
</div>

app/views/pages/tables/_dark.html.erb
<div class="card bg-default shadow">
  <div class="card-header bg-transparent border-0">
    <h3 class="text-white mb-0">Dark table</h3>
  </div>
  <div class="table-responsive">
    <table class="table align-items-center table-dark table-flush">
      <thead class="thead-dark">
        <tr>
          <th scope="col" class="sort" data-sort="name">Project</th>
          <th scope="col" class="sort" data-sort="budget">Budget</th>
          <th scope="col" class="sort" data-sort="status">Status</th>
          <th scope="col">Users</th>
          <th scope="col" class="sort" data-sort="completion">Completion</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody class="list">
        <tr>
          <th scope="row">
            <div class="media align-items-center">
              <a href="#" class="avatar rounded-circle mr-3">
                <%= image_tag "theme/bootstrap.jpg", alt: "..." %>
              </a>
              <div class="media-body">
                <span class="name mb-0 text-sm">Argon Design System</span>
              </div>
            </div>
          </th>
          <td class="budget">
            $2500 USD
          </td>
          <td>
            <span class="badge badge-dot mr-4">
              <i class="bg-warning"></i>
              <span class="status">pending</span>
            </span>
          </td>
          <td>
            <%= render 'pages/tables/avatar_group' %>
          </td>
          <td>
            <%= render partial: 'pages/tables/progress_bar', locals: {
              percent: 60,
              bg_class: 'bg-warning'
            } %>
          </td>
          <td class="text-right">
            <%= render 'pages/tables/row_actions' %>
          </td>
        </tr>
        <tr>
          <th scope="row">
            <div class="media align-items-center">
              <a href="#" class="avatar rounded-circle mr-3">
                <%= image_tag "theme/angular.jpg", alt: "..." %>
              </a>
              <div class="media-body">
                <span class="name mb-0 text-sm">Angular Now UI Kit PRO</span>
              </div>
            </div>
          </th>
          <td class="budget">
            $1800 USD
          </td>
          <td>
            <span class="badge badge-dot mr-4">
              <i class="bg-success"></i>
              <span class="status">completed</span>
            </span>
          </td>
          <td>
            <%= render 'pages/tables/avatar_group' %>
          </td>
          <td>
            <%= render partial: 'pages/tables/progress_bar', locals: {
              percent: 100,
              bg_class: 'bg-success'
            } %>
          </td>
          <td class="text-right">
            <%= render 'pages/tables/row_actions' %>
          </td>
        </tr>
        <tr>
          <th scope="row">
            <div class="media align-items-center">
              <a href="#" class="avatar rounded-circle mr-3">
                <%= image_tag "theme/sketch.jpg", alt: "..." %>
              </a>
              <div class="media-body">
                <span class="name mb-0 text-sm">Black Dashboard</span>
              </div>
            </div>
          </th>
          <td class="budget">
            $3150 USD
          </td>
          <td>
            <span class="badge badge-dot mr-4">
              <i class="bg-danger"></i>
              <span class="status">delayed</span>
            </span>
          </td>
          <td>
            <%= render 'pages/tables/avatar_group' %>
          </td>
          <td>
            <%= render partial: 'pages/tables/progress_bar', locals: {
              percent: 72,
              bg_class: 'bg-danger'
            } %>
          </td>
          <td class="text-right">
            <%= render 'pages/tables/row_actions' %>
          </td>
        </tr>
        <tr>
          <th scope="row">
            <div class="media align-items-center">
              <a href="#" class="avatar rounded-circle mr-3">
                <%= image_tag "theme/react.jpg", alt: "..." %>
              </a>
              <div class="media-body">
                <span class="name mb-0 text-sm">React Material Dashboard</span>
              </div>
            </div>
          </th>
          <td class="budget">
            $4400 USD
          </td>
          <td>
            <span class="badge badge-dot mr-4">
              <i class="bg-info"></i>
              <span class="status">on schedule</span>
            </span>
          </td>
          <td>
            <%= render 'pages/tables/avatar_group' %>
          </td>
          <td>
            <%= render partial: 'pages/tables/progress_bar', locals: {
              percent: 90,
              bg_class: 'bg-info'
            } %>
          </td>
          <td class="text-right">
            <%= render 'pages/tables/row_actions' %>
          </td>
        </tr>
        <tr>
          <th scope="row">
            <div class="media align-items-center">
              <a href="#" class="avatar rounded-circle mr-3">
                <%= image_tag "theme/vue.jpg", alt: "..." %>
              </a>
              <div class="media-body">
                <span class="name mb-0 text-sm">Vue Paper UI Kit PRO</span>
              </div>
            </div>
          </th>
          <td class="budget">
            $2200 USD
          </td>
          <td>
            <span class="badge badge-dot mr-4">
              <i class="bg-success"></i>
              <span class="status">completed</span>
            </span>
          </td>
          <td>
            <%= render 'pages/tables/avatar_group' %>
          </td>
          <td>
            <%= render partial: 'pages/tables/progress_bar', locals: {
              percent: 100,
              bg_class: 'bg-success'
            } %>
          </td>
          <td class="text-right">
            <%= render 'pages/tables/row_actions' %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/pages/tables/_foodlog.html.erb
<% content_for :foodlog do %>
 
  <style>
  body {
    min-height: 100%;
    }
    body, div, form, input, select { 
    /* padding: 0;
    margin: 0; */
    /* outline: none; */
    /* font-family: Roboto, Arial, sans-serif; */
    font-size: 14px;
    /* color: #666; */
    /* line-height: 22px; */
    }
    h1, h4 {
    margin: 15px 0 4px;
    /* font-weight: 400; */
    }
    h4 {
    margin: 20px 0 4px;
    /* font-weight: 400; */
    }
    
    .small {
    font-size: 10px;
    line-height: 18px;
    }
    .testbox {
    display: flex;
    justify-content: center;
    align-items: center;
    height: inherit;
    padding: 3px;
    }
    form {
    width: 100%;
    padding: 20px;
    /* background: #fff; */
    /* box-shadow: 0 2px 5px #ccc;  */
    }
    input {
    width: calc(100% - 10px);
    padding: 5px;
    border: 1px solid #ccc;
    border-radius: 3px;
    vertical-align: middle;
    }
    input:hover, textarea:hover, select:hover {
    outline: none;
    border: 1px solid #095484;
    background: #e6eef7;
    }
    .title-block select, .title-block input {
    margin-bottom: 10px;
    }
    select {
    padding: 7px 0;
    border-radius: 3px;
    border: 1px solid #ccc;
    background: transparent;
    }
    select, table {
    width: 100%;
    }
    option {
    background: #fff;
    }
    .day-visited, .time-visited {
    position: relative;
    }
    input[type="date"]::-webkit-inner-spin-button {
    display: none;
    }
    input[type="time"]::-webkit-inner-spin-button {
    margin: 2px 22px 0 0;
    }
    .day-visited i, .time-visited i, input[type="date"]::-webkit-calendar-picker-indicator {
    position: absolute;
    top: 8px;
    /* font-size: 20px; */
    }
    .day-visited i, .time-visited i {
    right: 5px;
    z-index: 1;
    /* color: #a9a9a9; */
    }
    [type="date"]::-webkit-calendar-picker-indicator {
    right: 0;
    z-index: 2;
    opacity: 0;
    }
    .question-answer label {
    display: block;
    padding: 0 20px 10px 0;
    }
    .question-answer input {
    width: auto;
    margin-top: -2px;
    }
    th, td {
    width: 18%;
    padding: 15px 0;
    border-bottom: 1px solid #ccc;
    text-align: center;
    vertical-align: unset;
    line-height: 18px;
    /* font-weight: 400; */
    word-break: break-all;
    }
    .first-col {
    width: 25%;
    text-align: left;
    }
    textarea {
    width: calc(100% - 6px);
    }
    .btn-block {
    margin-top: 20px;
    text-align: center;
    }
    button {
    width: 150px;
    padding: 10px;
    border: none;
    -webkit-border-radius: 5px; 
    -moz-border-radius: 5px; 
    border-radius: 5px; 
    background-color: #4553ff;
    font-size: 16px;
    color: #fff;
    cursor: pointer;
    }
    button:hover {
    background-color: #0666a3;
    }
    @media (min-width: 568px) {
    .title-block {
    display: flex;
    justify-content: space-between;
    }
    .title-block select {
    width: 30%;
    margin-bottom: 0;
    }
    .title-block input {
    width: 31%;
    margin-bottom: 0;
    }
    th, td {
    word-break: keep-all;
    }
    }
    </style>

<% end %>



<div class="card">
  <!-- Card header -->
  <div class="card-header border-0">
    <h3 class="mb-0">Food Logging</h3>
  </div>
  
  <!-- Light table -->
  <div class="table-responsive">
  <div class="container">
    
  <div class="testbox">

    <%= form_with url: get_edamam_data_path, local: true, method: :get do  %>
        <h1>Log your food</h1>
        <h4><span class="hovertext" data-hover="Choose from a mealtime of the day including Breakfast, Lunch, Snack, or Dinner."><i class="fa fa-info-circle" aria-hidden="true"></i></span> Type of Meal<span>*</span></h4>
     
          <%= select_tag "mealType",options_for_select([ "Breakfast", "Lunch", "Snack", "Dinner" ], if fields then fields.fetch(:mealType, "") end ), prompt: 'Choose one...',:required => true %>
        
        <h4><span class="hovertext" data-hover="Choose from a type of ethnic cuisine."><i class="fa fa-info-circle" aria-hidden="true"></i></span> Cuisine type<span>*</span></h4>

          <%= select_tag "cuisineType", options_for_select([ "American", "Asian", "British", "Caribbean", "Central Europe", "Chinese", "Eastern Europe",
          "French", "Indian", "Italian", "Japanese", "Kosher", "Mediterranean", "Mexican","Middle Eastern", "Nordic", "South American", "South East Asian" ], if fields then fields.fetch(:cuisineType, "") end ), prompt: 'Choose one...',:required => true %>
        <h4><span class="hovertext" data-hover="Write as many ingredients as you want in your recipe."><i class="fa fa-info-circle" aria-hidden="true"></i></span> Ingredients<span>*</span></h4>
        <%= text_field_tag "q",if fields then fields.fetch(:q, nil) end ,:required => true %>
       
        <div class="btn-block">
          <button type="submit" >View Meals</button>
        </div>
 
      <% end %>
    </div>
  </div>
    <%# <table class="table align-items-center table-flush">
      <thead class="thead-light">
        <tr>
          <th scope="col" class="sort" data-sort="name">Project</th>
          <th scope="col" class="sort" data-sort="budget">Budget</th>
          <th scope="col" class="sort" data-sort="status">Status</th>
          <th scope="col">Users</th>
          <th scope="col" class="sort" data-sort="completion">Completion</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody class="list">
        <tr>
          <th scope="row">
            <div class="media align-items-center">
              <a href="#" class="avatar rounded-circle mr-3">
                <%= image_tag "theme/bootstrap.jpg", alt: "..." %>
              <%# </a> %> 
              <%# <div class="media-body">
                <span class="name mb-0 text-sm">Argon Design System</span>
              </div>
            </div>
          </th> %>
          <%# <td class="budget">
            $2500 USD
          </td> %>
          <%# <td>
            <span class="badge badge-dot mr-4">
              <i class="bg-warning"></i>
              <span class="status">pending</span>
            </span>
          </td>
          <td>
            <%= render 'pages/tables/avatar_group' %>
          <%# </td>
          <td>
            <%= render partial: 'pages/tables/progress_bar', locals: {
              percent: 60,
              bg_class: 'bg-warning'
            } %>
          <%# </td>
          <td class="text-right">
            <%= render 'pages/tables/row_actions' %>
          <%# </td>
        </tr> %>
        <%# <tr>
          <th scope="row">
            <div class="media align-items-center">
              <a href="#" class="avatar rounded-circle mr-3">
                <%= image_tag "theme/angular.jpg", alt: "..." %>
              <%# </a>
              <div class="media-body">
                <span class="name mb-0 text-sm">Angular Now UI Kit PRO</span>
              </div>
            </div>
          </th>
          <td class="budget">
            $1800 USD
          </td> %> 
          <%# <td>
            <span class="badge badge-dot mr-4">
              <i class="bg-success"></i>
              <span class="status">completed</span>
            </span>
          </td>
          <td>
            <%= render 'pages/tables/avatar_group' %>
          <%# </td>
          <td>
            <%= render partial: 'pages/tables/progress_bar', locals: {
              percent: 100,
              bg_class: 'bg-success'
            } %>
          <%# </td>
          <td class="text-right">
            <%= render 'pages/tables/row_actions' %>
          <%# </td>
        </tr> %>
        <%# <tr> %>
          <%# <th scope="row">
            <div class="media align-items-center">
              <a href="#" class="avatar rounded-circle mr-3">
                <%= image_tag "theme/sketch.jpg", alt: "..." %>
              <%# </a>
              <div class="media-body">
                <span class="name mb-0 text-sm">Black Dashboard</span>
              </div>
            </div>
          </th>
          <td class="budget">
            $3150 USD
          </td>
          <td> %> 
            <%# <span class="badge badge-dot mr-4">
              <i class="bg-danger"></i>
              <span class="status">delayed</span>
            </span>
          </td>
          <td>
            <%= render 'pages/tables/avatar_group' %>
          <%# </td>
          <td>
            <%= render partial: 'pages/tables/progress_bar', locals: {
              percent: 72,
              bg_class: 'bg-danger'
            } %>
          <%# </td>
          <%# <td class="text-right">
            <%= render 'pages/tables/row_actions' %>
          <%# </td>
        </tr> %> 
        <%# <tr>
          <th scope="row">
            <div class="media align-items-center">
              <a href="#" class="avatar rounded-circle mr-3">
                <%= image_tag "theme/react.jpg", alt: "..." %>
              <%# </a>
              <div class="media-body">
                <span class="name mb-0 text-sm">React Material Dashboard</span>
              </div>
            </div>
          </th>
          <td class="budget">
            $4400 USD
          </td>
          <td>
            <span class="badge badge-dot mr-4">
              <i class="bg-info"></i>
              <span class="status">on schedule</span>
            </span> %>
          <%# </td> %> 
          <%# <td>
            <%= render 'pages/tables/avatar_group' %>
          <%# </td>
          <td>
            <%= render partial: 'pages/tables/progress_bar', locals: {
              percent: 90,
              bg_class: 'bg-info'
            } %>
          <%# </td>
          <td class="text-right">
            <%= render 'pages/tables/row_actions' %>
          <%# </td>
        </tr>
        <tr> %>
          <%# <th scope="row">
            <div class="media align-items-center">
              <a href="#" class="avatar rounded-circle mr-3">
                <%= image_tag "theme/vue.jpg", alt: "..." %>
              <%# </a>
              <div class="media-body">
                <span class="name mb-0 text-sm">Vue Paper UI Kit PRO</span>
              </div>
            </div>
          </th> %>
          <%# <td class="budget">
            $2200 USD
          </td>
          <td>
            <span class="badge badge-dot mr-4">
              <i class="bg-success"></i>
              <span class="status">completed</span>
            </span>
          </td>
          <td>
            <%= render 'pages/tables/avatar_group' %>
          <%# </td> %> 
          <%# <td>
            <%= render partial: 'pages/tables/progress_bar', locals: {
              percent: 100,
              bg_class: 'bg-success'
            } %>
          <%# </td> %>
          <%# <td class="text-right">
            <%= render 'pages/tables/row_actions' %>
          <%# </td>
        </tr>
      </tbody>
    </table>
  </div> %> 
  <!-- Card footer -->
  <%# <div class="card-footer py-4">
    <nav aria-label="...">
      <ul class="pagination justify-content-end mb-0">
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">
            <%= fa_icon 'angle-left' %>
            <%# <span class="sr-only">Previous</span>
          </a>
        </li>
        <li class="page-item active">
          <a class="page-link" href="#">1</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
        </li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item">
          <a class="page-link" href="#">
            <%= fa_icon 'angle-right' %>
            <%# <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>
    </nav>
  </div>  %>
  </div>
</div>

app/views/pages/tables/_progress_bar.html.erb
<div class="d-flex align-items-center">
  <span class="completion mr-2"><%= percent %>%</span>
  <div>
    <div class="progress">
    <div class="progress-bar <%= bg_class %>" role="progressbar" aria-valuenow="<%= percent %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= percent %>%;"></div>
    </div>
  </div>
</div>

app/views/pages/tables/_row_actions.html.erb
<div class="dropdown">
  <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= fa_icon 'ellipsis-v' %>
  </a>
  <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>